language: minimal

services:
  - docker

env:
  global:
    - DOCKER_ORG_NAME=tidair
    - DOCKER_REPO=pysmurf-server

stages:
  - name: deploy_docker
    if: tag IS present

jobs:
  include:
    - stage: deploy_docker
      name: "Deploy Docker Image"
      before_script:
        # Use the git tag to tag tag docker image
        - export DOCKER_TAG=`git describe --tags --always`
        # Login to docker
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ORG_NAME}" --password-stdin;

      script:
        # Build the docker image
        - ./build.sh ${DOCKER_TAG}