name: CD
on:
  push:
    tags:
      - '*'

jobs:
  deploy_docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Dockerhub
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: tidair
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the docker image
      - name: Build and push image to Dockerhub
        id: build
        shell: bash
        env:
          TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/build.sh
          . vars.env
          echo ::set-output name=release_name::"${release_name}"
          echo ::set-output name=release_description::"${release_description}"

      # Update the "RELEASES.md" table
      - name: Update RELEASES table
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_SLUG: ${{ github.repository }}
        run: ./scripts/update_release_table.sh

      # Create a new release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.build.outputs.release_name }}
          body: ${{ steps.build.outputs.release_description }}
          draft: false
          prerelease: false

      # Attach the original Dockerfile file as asset
      - name: Upload Dockerfile Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Dockerfile
          asset_name: Dockerfile
          asset_content_type: text/plain

      # Attach the original definitions.sh script as asset
      - name: Upload Definitions Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./definitions.sh
          asset_name: definitions.sh
          asset_content_type: text/plain
