on:
  push

jobs:
  deploy_docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Dockerhub
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: tidair
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Validate definitions
      - name: Validate definitions
        id: build
        shell: bash
        env:
          REPO_SLUG: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACLAB_TOKEN: ${{ secrets.SLACLAB_TOKEN }}
          DOCKERHUB_ORG_NAME: tidair
          DOCKERHUB_REPO: pysmurf-server
        run: |
          echo "Test:"
          echo "======="
          echo $(git ls-remote --refs --tag "https://$SLACLAB\_TOKEN@github.com/slaclab/cryo-det")
          echo "======="


