on:
  push

jobs:
  deploy_docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SLACLAB_KEY }}

      # Validate definitions
      - name: Validate definitions
        id: build
        shell: bash
        env:
          REPO_SLUG: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.SLACLAB_TOKEN }}
          DOCKERHUB_ORG_NAME: tidair
          DOCKERHUB_REPO: pysmurf-server
        run: ./validate.sh


